export enum ExceptionCode {
  AI_INTEGRATION_DATA_NOT_FOUND = 'AI-INT-NOT-FOUND',
  AI_INTEGRATION_MOCK_NAME_NOT_FOUND = 'AI-MOCK-NAME-NOT-FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL-SERVER-ERROR',
  AI_EXAMPLE_ANALYSIS_FAILED = 'AI_EXP_ANL_FAILED',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
}
