version: '3.8'

services:
  # NestJS Backend Application
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - /src:/app/src
      - /db:/app/db
      - /core:/app/core
      - /configs:/app/configs
    networks:
      - mpec_network
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mpec_db
      - POSTGRES_USER=mpec_user
      - POSTGRES_PASSWORD=mpec_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mpec_network
    restart: unless-stopped

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mpec.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres
    networks:
      - mpec_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  mpec_network:
    driver: bridge
